### PR TITLE
Fix links to pre-builts to always point to most recent version

### LINKED ISSUE #218: Do not point to v1.0 pre-builts in more recent versions of the documentation
Right now, we point to v1.0 pre-builts in various places in the documentation. The cleanest would be to replace all these links with version-specific links to Zenodo -- always pointing to the corresponding version. That would increase maintenance effort though and it would be brittle.

Instead, I suggest to always point to the newest version on Zenodo (i.e. using the version-unspecific link of Zenodo).

### PR DESCRIPTION
**Pull request by timtroendle**
Fixes #218  .

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [x] CHANGELOG updated
- [x] Minimal workflow tests pass
- [x] Tests added to cover contribution
- [x] Documentation updated
- [x] Configuration schema updated

### CODE REVIEW

**Review by zoltanmaric — APPROVED** [review]

**Review by brynpickering — COMMENTED** [review]
Does it make sense to also add the version number explicitly as a header / banner in the docs? E.g., we have it at as a subheading in the [Calliope docs](https://calliope.readthedocs.io/en/stable/)

**Comment by timtroendle** [comment]
It probably would make sense. Right now, the version number is not easily identifiable from the docs. In the best case, the version number would be visible on each page. Any ideas how to do that technically? Within readthedocs, mkdocs, or simply manually?

**Comment by brynpickering** [comment]
I think within mkdocs (https://www.mkdocs.org/user-guide/configuration/#extra). In rst with sphinx, the version can be referred to with `|version|` at any point in the docs.

**Comment by timtroendle** [comment]
The readthedocs theme does not support displaying version. So I simply added it manually to the home page. It won't be visible on any other page of course, but it's better than nothing.

**Review by brynpickering — APPROVED** [review]

**Pull request merged**
