### PR TITLE
Fix entsoe data load

### PR DESCRIPTION
**Pull request by brynpickering**
Supersedes #3 by bringing the branch 1.5years into the future and fixing issues.

In the 2019 OPSD load dataset we are using, there are no longer the invalid rows at the end of the dataset, instead we were cutting out perfectly good data...

### CODE REVIEW

**Comment by timtroendle** [comment]
I've seen you are still using that same old branch and you've updated it by merging in develop. In that case, can't you reuse the old pull request? It would be easier for me to trace what I said back then and what has been done and all that. If yes, can you reopen #3 and update it? If not, just ping me here and I'll do it here.

**Comment by brynpickering** [comment]
I got messy and realised too late that I had written this originally on my personal fork, and then made the latest updates on a branch in this repo. I will see about rebasing everything onto my fork and re-opening the other PR.

**Comment by timtroendle** [comment]
You should simply be able to pull the newer commits onto the branch in your fork. But don't do if it's too much work.

**Comment by brynpickering** [comment]
Closed to go back to #3. Sorry for the mess, @timtroendle

**Comment by timtroendle** [comment]
Thanks @brynpickering .

**Pull request closed without merging**
