### PR TITLE
Update feature-sector-coupling branch with changes from develop

### PR DESCRIPTION
**Pull request by timtroendle**
This is to keep the feature branch up to date with latest changes on develop.

### CODE REVIEW

**Comment by timtroendle** [comment]
The failing test is off. First, we did not change anything related to the test. Second, it worked with the `push` trigger, but not with the `pull_request` trigger. Third, I cannot reproduce locally. Let's wait a few hours and then retrigger, maybe the problem will resolve itself.

**Comment by brynpickering** [comment]
@timtroendle I think a fresh merge in from develop would be good here, then we can get it merged in over the following days rather than weeks!

**Comment by timtroendle** [comment]
As I am merging from `develop` here, this PR already contains all latest changes. @brynpickering , would you mind accepting this for me, then I will merge.

**Review by brynpickering — APPROVED** [review]

**Comment by timtroendle** [comment]
As there were merge conflicts that I could not resolve in the web editor, I needed to create a new PR #134. I am closing this PR in favour of #134.

**Pull request closed without merging**
