### PR TITLE
introduce data processing for annual heat demand

### LINKED ISSUE #88: Add cooking demand profiles and supply technologies
Separate to space heating and hot water demand is cooking demand. Although only accounting for a small amount of total demand, it has a distinct profile and needs to be decarbonised in many countries. As with any demand sector, whether to include this explicitly or not should be configurable (#86). 

Cooking is implemented in our sector-coupled sibling [here](https://github.com/calliope-project/euro-calliope-2.0/blob/main/src/construct/scale_hourly_cooking_profiles.py). It uses RAMP-cooking profiles for different countries. Cooking technologies are included in the heat techs YAML template in this repository's [sector-couple branch](https://github.com/calliope-project/euro-calliope/blob/bb8e7b71f10dd9d48cc63ad4178cd379f252ac4e/src/template/heat-techs.yaml#L210).

### LINKED ISSUE #101: Annual heat demand
The annual energy balances from a mix of data sources is the starting point to understand annual demands in many sectors. For building heat, this requires converting energy consumption to demand, based on assumptions of technology efficiency (e.g. 90-99% for gas boilers). The three building types considered are: households, commercial sector, other (agriculture, fisheries, and 'non-specified other'). 

The tasks are:

1. Get energy consumption per end-use in households (already processed in #100, with an added cleanup of renewables)
2. Get energy consumption per end-use in the commercial sector (requires JRC-IDEES and a specific Swiss dataset)
3. Clean up some countries outside the scope of input datasets (e.g. Iceland gets all its heat from geothermal, which we ignore)
4. Go from consumption to demand, using configurable efficiencies
5. Fill empty data from certain years with average, normalised end-use consumption scaled by Eurostat total household energy consumption.

This is undertaken in our sector-coupled sibling [here](https://github.com/calliope-project/euro-calliope-2.0/blob/main/src/construct/annual_heat_demand.py)

### PR DESCRIPTION
**Pull request by wwwuFei**
## annual heat demand

Fixes #101 
move from euro-calliope v2.0 (add`annual_heat_demand.py`, update `data-processing.smk` and `default.yaml`)

## cooking demand
Fixes #88 
Add `cooking-techs.yaml` (which was part of the heat techs YAML).
Move scale_hourly_cooking_profiles.py from euro-calliope v2.0

## Checklist
Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [ ] Minimal workflow tests pass
- [ ] Tests added to cover contribution
- [ ] Documentation updated
- [ ] Configuration schema updated

### CODE REVIEW

**Comment by FLomb** [comment]
Looks nice, but could you please update this branch based on the latest changes occurred in the [PR about annual energy balances](https://github.com/calliope-project/euro-calliope/pull/113) and test if all is still working fine? Even though you were already working on a branch based on the 'feature-annual-energy-balance' one, there's been some last changes to that (now merged in the master branch), e.g. in the names of the files generated, that might (or might not) affect what happens here (or in the other PR of yours, which follows this one).

For instance, "data/automatic/annual_energy_balances.tsv.gz" is now generated as ""data/automatic/**eurostat_**annual_energy_balances.tsv.gz". At first glance, this should not affect your PR because this file is only used internally in the `rule annual_energy_balances`, whose output file name isn't changed. But still, worth updating and testing if there's anything that needs a minor update.

**Comment by wwwuFei** [comment]
```
(euro-calliope) feiwufei@staff-net-cx-0538 euro-calliope % snakemake --use-conda --configfile="config/minimal.yaml"
AttributeError in line 44 of /Users/feiwufei/euro-calliope/rules/data-processing.smk:
'Namedlist' object has no attribute 'hh_end_use'
  File "/Users/feiwufei/euro-calliope/Snakefile", line 24, in <module>
  File "/Users/feiwufei/euro-calliope/rules/data-processing.smk", line 44, in <module>
```

@FLomb thanks for the suggestions and I rebased them on `calliope-project:feature-sector-coupling`, but got these errors as ☝️. I don't know how to fix it :(  Could you kind help fix it? 😄

**Comment by FLomb** [comment]
> ```
> (euro-calliope) feiwufei@staff-net-cx-0538 euro-calliope % snakemake --use-conda --configfile="config/minimal.yaml"
> AttributeError in line 44 of /Users/feiwufei/euro-calliope/rules/data-processing.smk:
> 'Namedlist' object has no attribute 'hh_end_use'
>   File "/Users/feiwufei/euro-calliope/Snakefile", line 24, in <module>
>   File "/Users/feiwufei/euro-calliope/rules/data-processing.smk", line 44, in <module>
> ```
> 
> @FLomb thanks for the suggestions and I rebased them on `calliope-project:feature-sector-coupling`, but got these errors when running local minimal test . I don't know how to fix it :( Could you kindly help fix it?

Hi @wwwuFei , you would need to change the way in which the `end_use` files are called, now that the rules for processing those have been modified with the introduction of wildcards. In short, you would just need to call the 2 files like this:

```
- hh_end_use = "data/automatic/eurostat-end_use.tsv.gz", 
- ch_end_use = "data/automatic/ch-end-use.xlsx"
```
The wildcards defined in `rule eurostat_data_ts` and `rule ch_data_xlsx` will then take care of the rest. However, this is not enough. You also need to take care of some changes occurred in the `utils` and of how those affect your `annual_heat_demand.py` script. For instance, instead of `get_alpha2` etc., there is now a single util function that handles all the country code modifications. You'd need to adjust your script to be up-to-date with such new formulation of the utils.

**Comment by timtroendle** [comment]
Closing this as it became stale.

**Pull request closed without merging**
