### PR TITLE
Fix localrules

### PR DESCRIPTION
**Pull request by timtroendle**
The localrules keyword breaks when a workflow is used as a module. This does not seem to get fixed, see https://github.com/snakemake/snakemake/issues/945

Instead, the recommended solution seems to be to use the localrule directive per rule.

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [x] CHANGELOG updated
- [x] Minimal workflow tests pass
- [x] Tests added to cover contribution
- [x] Documentation updated
- [x] Configuration schema updated

### CODE REVIEW

**Review by irm-codebase — APPROVED** [review]
I like this approach. Quite explicit.

However, localrule issues have been fixed in https://github.com/snakemake/snakemake/pull/2180, but we have not updated our snakemake version.

Still, this approach is way more maintainable since the directive is in each rule instead of a separate line.

**Comment by timtroendle** [comment]
Thanks for the review @irm-codebase. Just to add: we did update Snakemake recently and are on almost the newest version (3 micro updates have been published since, :D).

And yes, the fix is the `localrule` thing, but the `localrules` is still broken. I think `localrules` should be deprecated, but that's for the Snakemake devs to decide.

**Review by brynpickering — APPROVED** [review]
Add changelog entry?

**Comment by timtroendle** [comment]
Yes, that makes sense.

**Pull request merged**
