### PR TITLE
Update docs and remove scenarios.yaml

### LINKED ISSUE #230: Imports aren't properly documented
Following updates in #145, imports aren't properly documented. File names of the previously existing imports (transmission links) are broken. All new imports aren't mentioned at all.

### PR DESCRIPTION
**Pull request by brynpickering**
Fixes #230 & #236. Reverts #209.

Since we are now modular, it's impossible to have any one file that links to the contents of multiple other files (as `scenarios.yaml` was doing in grouping overrides). So, we have to remove this file and instead document how one would create their own scenarios by grouping overrides.

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [x] CHANGELOG updated
- [x] Minimal workflow tests pass
- [x] Tests added to cover contribution
- [x] Documentation updated
- [x] Configuration schema updated

### CODE REVIEW

**Comment by timtroendle** [comment]
@brynpickering is this ready to be reviewed again?

**Comment by brynpickering** [comment]
Yes!

**Review by timtroendle — APPROVED** [review]
I like it now!

One small thing needs to be fixed: all code boxes (yaml and python) in the overrides section of customisation.md are broken (have a look at the readthedocs preview). Not sure what's going on but it's basically unreadable right now.

**Comment by brynpickering** [comment]
Hmm, the code blocks render just fine when I build it locally:

image

**Comment by timtroendle** [comment]
It works for me too. Also, I figured just now, that these code blocks are broken in other parts of the documentation on readthedocs, too. That's weird. Is it possible that this is a glitch in the built?

**Comment by brynpickering** [comment]
I checked the supposed dead markdown link (https://open-power-system-data.org/) and it isn't dead.

**Review by timtroendle — APPROVED** [review]
Thanks a lot for following up on this, @brynpickering . It all looks good to me now, apart from the erratic behaviour of the Markdown link check. We need to investigate what's going on or otherwise remove it. It's suspicious that it's consistently open-power-system-data that's failing.

**Pull request merged**
