### PR TITLE
Use more recent curl version to fix hydro basins download

### LINKED ISSUE #267: Error in rule `download_basins_database`
### What happened?

When executing the euro-calliope workflow in Linux, I get an error when trying to download `raw-hydro-basins.zip` from Dropbox.

```
Error in rule download_basins_database:
    jobid: 91
    output: data/automatic/raw-hydro-basins.zip
    conda-env: .snakemake/conda/9ce49abf6f4c5d02c089fd3ffcd28a1a
    shell:
        curl -sLo data/automatic/raw-hydro-basins.zip 'https://www.dropbox.com/sh/hmpwobbz9qixxpe/AADeU9iCgMd3ZO1KgrFmfWu6a/HydroBASINS/standard/eu/hybas_eu_lev07_v1c.zip?dl=1'
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

The above terminal output is not very helpful - no specific error message. 

I executed the command `curl -sLo data/automatic/raw-hydro-basins.zip 'https://www.dropbox.com/sh/hmpwobbz9qixxpe/AADeU9iCgMd3ZO1KgrFmfWu6a/HydroBASINS/standard/eu/hybas_eu_lev07_v1c.zip?dl=1'` in my basic conda env and got no problem. When switching to the environment managed by snakemake, it failed.

Had a look at the logs (store it by calling curl -sLo .... >curl_log.log 2>&1"). In the log, I saw `HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)`

Calling curl with `--http1.1` solves the problem. Dropbox offers http2, though, so what is causing the problem?

### Version

1.2.0.dev

### PR DESCRIPTION
**Pull request by jnnr**
Fixes #267. 

## Checklist

- [x] CHANGELOG updated
- [x] Minimal workflow tests pass (on jnnr's linux machine)
- [x] Tests added to cover contribution
- [x] Documentation updated
- [x] Configuration schema updated

### CODE REVIEW

**Comment by jnnr** [comment]
Thanks for your review, @timtroendle! The minimal workflow is still running. I'll check the box if it finishes successfully.

**Comment by jnnr** [comment]
Unfortunately, when running the minimal workflow I get a new error:
```
Error in rule download_raw_load:
    jobid: 75
    output: data/automatic/raw-load-data.csv
    conda-env: /home/jlauner/repos/envs/snakemake/euro-calliope/eaf9c112ec3dcd126c6a04c49f3548b5_
    shell:
        curl -sLo data/automatic/raw-load-data.csv 'https://data.open-power-system-data.org/time_series/2019-06-05/time_series_60min_stacked.csv'
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```
and
```
Error in rule download_capacity_factors_wind_and_solar:
    jobid: 53
    output: data/automatic/capacityfactors/wind-onshore-timeseries.nc
    conda-env: /home/jlauner/repos/envs/snakemake/euro-calliope/eaf9c112ec3dcd126c6a04c49f3548b5_
    shell:
        curl -sLo data/automatic/capacityfactors/wind-onshore-timeseries.nc 'https://zenodo.org/record/3899687/files/wind-onshore-timeseries.nc?download=1'
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

**Comment by timtroendle** [comment]
They have also released version 8.7.1 just a few days ago. In the absence of other solutions, you could also try updating again.

**Comment by sjpfenninger** [comment]
I have just re-run again after wiping all build and data files to ensure everything is downloaded, and for me, it works with curl `8.6.0` (`hca28451_0`).

I do have another issue that I haven't raised so far but that I always had to fix to get the shell environment working to begin with (on linux only, #321).

**Comment by jnnr** [comment]
I ran this again on my own computer and esm1. On my own computer, at first run I encountered the above errors again when downloading data/automatic/capacityfactors/wind-onshore-timeseries.nc and data/automatic/raw-load-data.csv. After starting the workflow again it succeeded however without me conciously changing anything. 

So I'd suggest we count this as resolved and open a new issue if problems persist.

**Review by brynpickering — APPROVED** [review]

**Pull request merged**
