### PR TITLE
Update Calliope to 0.6.6

### LINKED ISSUE #73: Update to Calliope 0.6.7
Changes since 0.6.5:
https://calliope.readthedocs.io/en/stable/history.html#id1

### PR DESCRIPTION
**Pull request by timtroendle**
Fixes #73.

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [x] Minimal workflow tests pass
- [x] Tests added to cover contribution
- [x] Documentation updated
- [x] Configuration schema updated

### CODE REVIEW

**Comment by timtroendle** [comment]
While this works, there are staggering 19936 warnings in the test report. Some come from ruamel and some from NumPy 1.20, but most of them come from pyomo:

```
test_model.py: 19652 warnings
  /Users/trtim/Develop/euro-calliope/.snakemake/conda/8c2a862642b61c6eaabb146b1c24d816/lib/python3.8/site-packages/pyomo/solvers/plugins/solvers/direct_or_persistent_solver.py:219: DeprecationWarning:

  Deprecated, pass a TempConstr or use Model.addLConstr
```

**Comment by brynpickering** [comment]
The warning you're coming across is being passed on by Pyomo, since it is related to their interface with Gurobi... Maybe an older `gurobipy` version would deal with this?

**Review by brynpickering — COMMENTED** [review]
`0.6.6.post1` is the only version of `0.6.6` available on conda-forge (the need for the `post1` was due to an error in publishing the pip wheel, rather than any change in Calliope). I would say there's less confusion by going for `0.6.6`.

If this PR waits 1 week, we could also just leapfrog to v0.6.7...

**Comment by timtroendle** [comment]
I think I'd rather stick to `0.6.6.post1` as it's more specific. Also, I am not exactly sure where it's fine to abbreviate it with `0.6.6` and where not. In conda envs, it should be fine. But is it also fine in the `model.yaml`?

We can ignore this is if we wait for 0.6.7 of course. Will 0.6.7 have any of the breaking changes of 0.7.0 or is it mainly a drop-in replacement? Do you think 0.6.7 will solve the deprecation warning?

**Comment by brynpickering** [comment]
It's mainly a drop-in replacement. The tests won't spit out the deprecation warning you mentioned because that warning is explicitly ignored in the `pytest.ini` of 0.6.7.

**Comment by timtroendle** [comment]
Ok, let's wait for 0.6.7 in that case.

**Pull request closed without merging**
